### ISSUE TITLE
Ensuring "absent" on PHP extensions yields error

### ISSUE THREAD

**Issue by mbrodala** [voxpupuli/puppet-php#181]
Given the following snippet (Hiera):

``` yaml
php::extensions:
  xdebug:
    ensure: absent
```

Yields the following error on every PHP invocation:

> Failed loading /usr/lib/php5/20121212+lfs/xdebug.so:  /usr/lib/php5/20121212+lfs/xdebug.so: cannot open shared object file: No such file or directory

This is caused by `zend_extension=xdebug.so` not being commented out in `/etc/php5/mods-available/xdebug.ini`. Manually doing this fixes the error.
