### ISSUE TITLE
Debian 9 (Stretch) support

### ISSUE THREAD

**Issue by SimonHoenscheid** [voxpupuli/puppet-php#439]
I am currently migrating my servers to Debian 9, I had a closer look at the pull requests in the last weeks but did not see direct Debian 9 support, besides that the Sury repo was added. Am I overseeing any commits? Otherwise I would be happy to add the support for Debian 9.

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: All supported versions
- Ruby: depends, look above
- Distribution: debian 9
- Module version: 5.3.0

## How to reproduce (e.g Puppet code you use)

Running this module on Debian Stretch

## What are you seeing

Module tries to install php5

## What behaviour did you expect instead

module installs php7.0

**Comment by c33s** [comment]
the module work for debian9 but i think you have to add some config in hiera for it.

how are you using the module? do you use hiera? do you just include `php` or do you add some kind of config?
have you enabled `manage_repos`? if yes you should disable it because on debian9 with `managed repos = true` you end up with dotdeb.org which is not compatible for debian9
which exact php version it tries to install? 

try to add the following to your hiera:
```
php::manage_repos: false
```
then you should end up with the native php 7.0 but my personal tip would be to go for the following
```
php::globals::php_version: '7.1'
php::manage_repos: true
php::repo::debian::location: https://packages.sury.org/php/
php::repo::debian::release: "%{::facts.os.distro.codename}"
php::repo::debian::repos: main
php::repo::debian::key:
  id: DF3D585DB8F0EB658690A554AC0E47584A7A714D
  source: https://packages.sury.org/php/apt.gpg
php::repo::debian::sury: false
```
then you should get surys php7.1

i am currently working on the debian repo refactoring, so i think it would only interfere my work. https://github.com/voxpupuli/puppet-php/pull/436

if you really want to help you can have a look at https://github.com/voxpupuli/puppet-php/issues/433
i want to try the module with different vagrant machines and debug why the tests are suddenly broken. because of a reason i don't know the wrong libdb is required:

-    in debian7 wheezy https://packages.debian.org/wheezy/php5-cli is build against https://packages.debian.org/wheezy/libdb5.1
-    in debian8 jessie https://packages.debian.org/jessie/php5-cli against https://packages.debian.org/jessie/libdb5.3
-    in debian9 stretch (which is currently not in the build map) there is no php5-cli until we integrate the sury repo with auto usage of it.

**Comment by bastelfreak** [comment]
Hi @SimonHoenscheid. Our idea was to first fix / merge https://github.com/voxpupuli/puppet-php/pull/436 and afterwards implement Debian 9 support. Are you interested in contributing? You can help reviewing #436 or hance our acceptence test matrix

**Comment by bastelfreak** [comment]
ups, @c33s was a minute faster.

**Comment by SimonHoenscheid** [comment]
Hi @c33s this is interesting. I just followed the default config example. Which worked fine for jessie and also should work for stretch with the default php 7.0 from debian itself . I added the code needed and added the tests. PR in a bit.

**Comment by SimonHoenscheid** [comment]
@bastelfreak sorry just saw your comment, I am happy to help anyhow.

**Comment by SimonHoenscheid** [comment]
@bastelfreak something that got my attention during adding the code were the conditions attachd to the OSes, they are more complex than they need to be, maybe its also a good thing to clean them up later

**Comment by c33s** [comment]
@SimonHoenscheid can you please post your config here? i would be interested in how you called it exactly

**Comment by SimonHoenscheid** [comment]
` include '::php'
`
```
#PHP
php::ensure: latest
php::fpm: true
php::dev: true
php::fpm::settings:
  'PHP/max_execution_time': '90'
  'PHP/max_input_time': '300'
  'PHP/memory_limit': '64M'
  'PHP/post_max_size': '32M'
  'PHP/upload_max_filesize': '32M'
  'Date/date.timezone': 'Europe/Berlin'
  'PHP/short_open_tag': 'On'
  'PHP/always_populate_raw_post_data': '-1'


php::extensions:
  apcu: {
    package_prefix: 'php-'
  }
  curl: {}
  gd: {}
  imagick: {
    package_prefix: 'php-'
  }
  imap: {}
  intl: {}
  mcrypt: {}
  memcache: {
    package_prefix: 'php-'
  }
  mysql: {}
  pspell: {}
  recode: {}
  snmp: {}
  sqlite3: {}
  tidy: {}
  xmlrpc: {}
  xsl: {}
php::fpm::pools:
  www:
    listen: '/var/run/fpmpool-www.socket'
    listen_owner: 'www-data'
    listen_group: 'www-data'
    pm: 'dynamic'
    pm_max_children: '25'
    pm_max_requests: '500'
    pm_max_spare_servers: '20'
    pm_min_spare_servers: '10'
    pm_start_servers: '10'
    request_terminate_timeout: '60s'
    pm_status_path: '/fpm-status'
    rlimit_core: 'unlimited'
    rlimit_files: '32000'
    catch_workers_output: 'yes'
```
