### ISSUE TITLE
"php::manage_repos: true" causes failure on Ubuntu 18.04, needs newer puppetlabs-apt version(>=5.0.0)

### ISSUE THREAD

**Issue by l-lotz** [voxpupuli/puppet-php#467]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.4-1bionic
- Ruby: 
- Distribution: Ubuntu 18.04
- Module version: 6.0.0

## How to reproduce (e.g Puppet code you use)
Set the following in hiera:
php::manage_repos: true

## What are you seeing
PPA installation fails because package "python-software-properties" does not exist.

## What behaviour did you expect instead
clean puppet run that installs ondrej ppa

## Output log
```
    int: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install python-software-properties' returned 100: Reading package lists...
    int: Building dependency tree...
    int: Reading state information...
    int: Package python-software-properties is not available, but is referred to by another package.
    int: This may mean that the package is missing, has been obsoleted, or
    int: Notice: /Stage[main]/Php::Repo::Ubuntu/Apt::Ppa[ppa:ondrej/php]/Exec[add-apt-repository-ppa:ondrej/php]: Dependency Package[python-software-properties] has failures: true
    int: is only available from another source
    int: However the following packages replace it:
    int:   software-properties-common
    int:
    int: E: Package 'python-software-properties' has no installation candidate
    int: Error: /Stage[main]/Php::Repo::Ubuntu/Apt::Ppa[ppa:ondrej/php]/Package[python-software-properties]/ensure: change from 'purged' to 'present' failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install python-software-properties' returned 100: Reading package lists...
    int: Building dependency tree...
    int: Reading state information...
    int: Package python-software-properties is not available, but is referred to by another package.
    int: This may mean that the package is missing, has been obsoleted, or
    int: is only available from another source
    int: However the following packages replace it:
    int:   software-properties-common
    int:
    int: E: Package 'python-software-properties' has no installation candidate
    int: Warning: /Stage[main]/Php::Repo::Ubuntu/Apt::Ppa[ppa:ondrej/php]/Exec[add-apt-repository-ppa:ondrej/php]: Skipping because of failed dependencies
    int: Notice: /Stage[main]/Php::Repo::Ubuntu/Apt::Ppa[ppa:ondrej/php]/File[/etc/apt/sources.list.d/ondrej-ubuntu-php-bionic.list]: Dependency Package[python-software-properties] has failures: true
    int: Warning: /Stage[main]/Php::Repo::Ubuntu/Apt::Ppa[ppa:ondrej/php]/File[/etc/apt/sources.list.d/ondrej-ubuntu-php-bionic.list]: Skipping because of failed dependencies
```

## Any additional information you'd like to impart
This is fixed with puppetlabs/apt >= 5.0.0, but puppet/php metadata.json requires puppetlabs/apt<5.0.0

Workaround:
Set apt::ppa_package: 'software-properties-common'
