### ISSUE TITLE
sqlsrv and pdo_sqlsrv will not be installed

### ISSUE THREAD

**Issue by kszyma** [voxpupuli/puppet-php#721]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.24.0
- Ruby: 2.7.7p221
- Distribution: Ubuntu 20.04.6
- Module version: 10.0.0

## How to reproduce (e.g Puppet code you use)

Configure php 8.1 within hiera like this:

```
  [...]
  manage_repos: false
  extensions:
  [...]
    sqlsrv:
      provider: 'pecl'
    pdo_sqlsrv:
      provider: 'pecl'
```

## What are you seeing

pdo_sqlsrv and sqlsrv-Module will not be installed.

## What behaviour did you expect instead

That both will be installed. If i do it with

```
pecl install sqlsrv
pecl install pdo_sqlsrv
```

everything will work fine.
